export const inspectorHelp = {
  forecastHorizonDays: 'Number of future days to predict after the end of the uploaded daily history. Max 730 days.',
  holdoutDays: 'Holds back the last N historical days as a scored test set. These days are excluded from training and used for the MAPE and MAE accuracy checks.',
  confidence: 'Controls the width of the forecast interval shown around the forecast line. Higher percentages create a wider confidence band.',
  weeklySeasonality: 'Models recurring day-of-week patterns, such as weekdays behaving differently from weekends.',
  monthlySeasonality: 'Models an approximate 30.5-day repeating cycle. Use this only when the series shows a meaningful monthly rhythm beyond weekly and yearly effects.',
  yearlySeasonality: 'Models recurring annual patterns such as seasonal peaks, troughs, and year-over-year recurring demand swings.',
  holidayCalendar: 'Selects the built-in holiday calendar Prophet should include automatically before any custom holidays are added.',
  holidayStrength: 'Controls how strongly holiday effects are allowed to influence the forecast. Higher values let holidays move the model more aggressively.',
  customHolidayName: 'Name used to identify this holiday effect in the forecast inputs and component outputs.',
  customHolidayDate: 'Calendar date for the holiday or event that should influence the forecast.',
  customHolidayLowerWindow: 'Number of days before the holiday that should inherit the same holiday effect.',
  customHolidayUpperWindow: 'Number of days after the holiday that should inherit the same holiday effect.',
  customHolidayStrength: 'Controls how strongly this specific custom holiday can influence the forecast.',
  seasonalityMode: 'Additive patterns move the forecast by a fixed amount. Multiplicative patterns scale up and down with the overall trend level.',
  growth: 'Linear growth leaves the trend unconstrained. Logistic growth uses upper and lower limits so the forecast stays within a bounded range.',
  changepointPriorScale: 'Controls how freely the long-term trend can bend at changepoints. Higher values allow faster shifts but increase overfitting risk.',
  changepointRange: 'Defines how late in the history Prophet may place automatic changepoints. Lower values force trend changes earlier; higher values allow them later.',
  changepointCount: 'Maximum number of automatic trend changes Prophet may place within the allowed changepoint window.',
  mcmcSamples: 'Number of Bayesian sampling draws. Leave this at 0 for the faster default fit. Higher values increase runtime and uncertainty detail.',
  defaultCap: 'Upper forecast limit used when the trend shape is logistic. This limit applies to the fitted history and all forecast days.',
  defaultFloor: 'Lower forecast limit used when the trend shape is logistic. This floor applies to the fitted history and all forecast days.',
  manualChangepoints: 'Optional comma-separated YYYY-MM-DD dates where the trend is allowed to change explicitly.',
  customSeasonalityName: 'Short name used to identify this custom repeating pattern.',
  customSeasonalityPeriod: 'Cycle length in days for this custom repeating pattern.',
  customSeasonalityFourier: 'Pattern detail. Higher values allow a more complex repeating shape.',
  customSeasonalityStrength: 'Pattern strength. Higher values let this custom cycle influence the forecast more strongly.',
  customSeasonalityMode: 'Additive patterns move the forecast by a fixed amount. Multiplicative patterns scale with the trend level.'
}
